version: '3'

services:

  database:
    container_name: database
    image: mysql
    restart: on-failure
    environment:
      MYSQL_USER: webshop
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: webproject
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - app-network
    volumes:
      - my-volume:/var/lib/mysql

  backend:
    container_name: backend
    depends_on:
      - database
    restart: on-failure
    links:
      - database
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=developer"
      # remove port for production
    ports:
      - 8080:8080
    networks:
      - app-network

#  frontend:
#    container_name: frontend
#    restart: on-failure
#    links:
#      - backend
#    build:
#      context: ./frontend/
#      dockerfile: Dockerfile
#    networks:
#      - app-network
#    ports:
#      - 80:80
#      - 443:443

networks:
  app-network:

volumes:
  my-volume:
