spring:
  application:
    name: webproject
  profiles:
    active: developer
  datasource:
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
    driver-class-name: org.h2.Driver


server:
  port: 8080


